// Connect to the database 'userdb' before running this script if running manually in shell.
// Or run with: mongosh "mongodb+srv://..." insert_hosts.js

const hosts = [
  {
    "_class": "com.airbnb.user.model.User",
    "userId": "de2c1f58-bf7a-430a-a606-5d0c926916a5",
    "email": "host1@gmail.com",
    "password": "$2b$12$qfvtKxBnraUKMWRTajeKtuqh861kyso7Wb6AtYPairQltIsYIKWuW", // hostpassword1
    "firstName": "Host1",
    "lastName": "User",
    "phoneNumber": "01234567891",
    "profileImage": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=800&auto=format&fit=crop",
    "bio": "Experienced host offering stays in Phi Phi.",
    "role": "HOST",
    "status": "ACTIVE",
    "emailVerified": true,
    "verificationStatus": "APPROVED",
    "verificationRequestedAt": new Date(),
    "verifiedAt": new Date(),
    "street": "Phi Phi Islands",
    "area": "Krabi",
    "village": "Phi Phi Don",
    "district": "Krabi",
    "division": "South",
    "city": "Krabi",
    "country": "Thailand",
    "zipCode": "81000",
    "latitude": 7.7407,
    "longitude": 98.7784,
    "superhost": false,
    "hostDisplayName": "Host1's Phi Phi Retreat",
    "hostAbout": "Enjoy the crystal clear waters of Phi Phi from our cozy retreat.",
    "hostingSince": new Date(),
    "preferredCheckInTime": "14:00",
    "preferredCheckOutTime": "11:00",
    "responseTimeHours": 2,
    "houseRules": "No smoking. Quiet hours 10pm-8am.",
    "propertyTypesOffered": ["Villa", "Bungalow"],
    "offeringHighlights": ["Beachfront", "Wifi", "AC"],
    "hostPortfolioImages": [],
    "guestCapacity": 4,
    "bedCount": 2,
    "bedTypes": ["KING_BED", "QUEEN_BED"],
    "nightlyRateUsd": 120.0,
    "totalListings": 1,
    "averageRating": 4.8,
    "reviewCount": 12,
    "responseRate": 95.0,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_class": "com.airbnb.user.model.User",
    "userId": "bb21342f-105f-4f40-a5c0-18364b0eff00",
    "email": "host2@gmail.com",
    "password": "$2b$12$upun9kYjDTbc7b7k2.siIuIURlprn0BrhODbQRIFCzgpEhIMGXlP.", // hostpassword2
    "firstName": "Host2",
    "lastName": "User",
    "phoneNumber": "01234567892",
    "profileImage": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=800&auto=format&fit=crop",
    "bio": "Welcome to Krabi! I love hosting travelers.",
    "role": "HOST",
    "status": "ACTIVE",
    "emailVerified": true,
    "verificationStatus": "APPROVED",
    "verificationRequestedAt": new Date(),
    "verifiedAt": new Date(),
    "street": "Ao Nang",
    "area": "Krabi",
    "village": "Ao Nang",
    "district": "Krabi",
    "division": "South",
    "city": "Krabi",
    "country": "Thailand",
    "zipCode": "81180",
    "latitude": 8.0863,
    "longitude": 98.9063,
    "superhost": false,
    "hostDisplayName": "Host2's Krabi Villa",
    "hostAbout": "Relax in our modern villa near the beach.",
    "hostingSince": new Date(),
    "preferredCheckInTime": "15:00",
    "preferredCheckOutTime": "11:00",
    "responseTimeHours": 1,
    "houseRules": "No parties.",
    "propertyTypesOffered": ["Villa", "Apartment"],
    "offeringHighlights": ["Pool", "Kitchen"],
    "hostPortfolioImages": [],
    "guestCapacity": 6,
    "bedCount": 3,
    "bedTypes": ["KING_BED", "QUEEN_BED", "SOFA_BED"],
    "nightlyRateUsd": 150.0,
    "totalListings": 2,
    "averageRating": 4.9,
    "reviewCount": 25,
    "responseRate": 98.0,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_class": "com.airbnb.user.model.User",
    "userId": "d8dba18a-1faa-47a9-98cc-4aab73c513e2",
    "email": "host3@gmail.com",
    "password": "$2b$12$unqjiUNERpcpFYETmPVwH.hw8gqzTcMtmX5reHjNmE8Zc9Y0HlNKO", // hostpassword3
    "firstName": "Host3",
    "lastName": "User",
    "phoneNumber": "01234567893",
    "profileImage": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=800&auto=format&fit=crop",
    "bio": "Island life in Maafushi.",
    "role": "HOST",
    "status": "ACTIVE",
    "emailVerified": true,
    "verificationStatus": "APPROVED",
    "verificationRequestedAt": new Date(),
    "verifiedAt": new Date(),
    "street": "Main Street",
    "area": "Maafushi",
    "village": "Maafushi",
    "district": "Kaafu Atoll",
    "division": "Central",
    "city": "Maafushi",
    "country": "Maldives",
    "zipCode": "08090",
    "latitude": 3.9413,
    "longitude": 73.4907,
    "superhost": true,
    "hostDisplayName": "Host3's Maafushi Haven",
    "hostAbout": "Experience the Maldives like a local.",
    "hostingSince": new Date(),
    "preferredCheckInTime": "13:00",
    "preferredCheckOutTime": "10:00",
    "responseTimeHours": 3,
    "houseRules": "Respect local customs.",
    "propertyTypesOffered": ["Guesthouse", "Room"],
    "offeringHighlights": ["Ocean view", "Breakfast included"],
    "hostPortfolioImages": [],
    "guestCapacity": 2,
    "bedCount": 1,
    "bedTypes": ["KING_BED"],
    "nightlyRateUsd": 80.0,
    "totalListings": 3,
    "averageRating": 4.7,
    "reviewCount": 40,
    "responseRate": 90.0,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_class": "com.airbnb.user.model.User",
    "userId": "f00c8c71-494e-4f06-96cc-b803f5af32b5",
    "email": "host4@gmail.com",
    "password": "$2b$12$E1zfiZmtthsF3xw3w69sVOKOn8WAl8iT72j6qPBKoUBmv7bS.8BuS", // hostpassword4
    "firstName": "Host4",
    "lastName": "User",
    "phoneNumber": "01234567894",
    "profileImage": "https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=800&auto=format&fit=crop",
    "bio": "Listing in the beautiful Ba Na Hills.",
    "role": "HOST",
    "status": "ACTIVE",
    "emailVerified": true,
    "verificationStatus": "APPROVED",
    "verificationRequestedAt": new Date(),
    "verifiedAt": new Date(),
    "street": "Golden Bridge Rd",
    "area": "Ba Na Hills",
    "village": "Hoa Vang",
    "district": "Da Nang",
    "division": "Central",
    "city": "Da Nang",
    "country": "Vietnam",
    "zipCode": "550000",
    "latitude": 15.9965,
    "longitude": 107.9942,
    "superhost": false,
    "hostDisplayName": "Host4's Ba Na Hills Resort",
    "hostAbout": "Luxury stay near the Golden Bridge.",
    "hostingSince": new Date(),
    "preferredCheckInTime": "14:00",
    "preferredCheckOutTime": "12:00",
    "responseTimeHours": 1,
    "houseRules": "No pets.",
    "propertyTypesOffered": ["Resort", "Hotel"],
    "offeringHighlights": ["Cable car access", "Mountain view"],
    "hostPortfolioImages": [],
    "guestCapacity": 4,
    "bedCount": 2,
    "bedTypes": ["QUEEN_BED", "QUEEN_BED"],
    "nightlyRateUsd": 200.0,
    "totalListings": 5,
    "averageRating": 4.6,
    "reviewCount": 8,
    "responseRate": 92.0,
    "createdAt": new Date(),
    "updatedAt": new Date()
  },
  {
    "_class": "com.airbnb.user.model.User",
    "userId": "3c5e6a39-adb3-45d0-886f-1b6db283183a",
    "email": "host5@gmail.com",
    "password": "$2b$12$cLPsY7eqiv0C6Nc0aZy0c.HXtDnAC5RhidDGpElFM8sCZCYE6eZnq", // hostpassword5
    "firstName": "Host5",
    "lastName": "User",
    "phoneNumber": "01234567895",
    "profileImage": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    "bio": "Warm hospitality in Kashmir.",
    "role": "HOST",
    "status": "ACTIVE",
    "emailVerified": true,
    "verificationStatus": "APPROVED",
    "verificationRequestedAt": new Date(),
    "verifiedAt": new Date(),
    "street": "Dal Lake",
    "area": "Srinagar",
    "village": "Srinagar",
    "district": "Srinagar",
    "division": "Kashmir",
    "city": "Srinagar",
    "country": "India",
    "zipCode": "190001",
    "latitude": 34.0837,
    "longitude": 74.7973,
    "superhost": true,
    "hostDisplayName": "Host5's Kashmir Cottage",
    "hostAbout": "Traditional houseboat stay on Dal Lake.",
    "hostingSince": new Date(),
    "preferredCheckInTime": "12:00",
    "preferredCheckOutTime": "10:00",
    "responseTimeHours": 4,
    "houseRules": "Shoes off inside.",
    "propertyTypesOffered": ["Houseboat", "Cottage"],
    "offeringHighlights": ["Lake view", "Shikara ride"],
    "hostPortfolioImages": [],
    "guestCapacity": 5,
    "bedCount": 3,
    "bedTypes": ["KING_BED", "TWIN_BED", "TWIN_BED"],
    "nightlyRateUsd": 90.0,
    "totalListings": 4,
    "averageRating": 4.95,
    "reviewCount": 60,
    "responseRate": 99.0,
    "createdAt": new Date(),
    "updatedAt": new Date()
  }
];

// Execute Insert
try {
  // Check if we are connected to the correct database or switch to it if in shell
  // db = db.getSiblingDB('userdb');

  const result = db.users.insertMany(hosts);
  printjson(result);
  print("Successfully inserted " + hosts.length + " hosts.");
} catch (e) {
  print("Error inserting hosts:");
  print(e);
}
