server:
  port: 8085

spring:
  application:
    name: availability-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb+srv://tanim:tanim@cluster0.mongodb.net/availabilitydb?retryWrites=true&w=majority&appName=ISD+Airbnb}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.airbnb.availability: DEBUG
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
